# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  - repo: self

variables:
  tag: 35

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'  # utiliza una imagen de máquina virtual de Ubuntu para ejecutar el trabajo
    steps:
    # Copia los archivos de la aplicación al directorio de trabajo del agente
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    # Publica los artefactos de construcción
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)' # ruta donde se publicarán los artefactos de construcción
        ArtifactName: 'manifests' # nombre del artefacto que se publicará
        publishLocation: 'Container' # indica que los artefactos se publicarán en un contenedor de Azure DevOps

# en este punto, los artefactos de construcción se han publicado y están listos para ser utilizados en la siguiente etapa
# agora, se define la etapa de despliegue, donde se descargarán los artefactos publicados y se aplicarán los manifiestos de Kubernetes
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Descarga los artefactos publicados en la etapa anterior
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: current
        artifactName: manifests
        itemPattern: '**/*.yaml'
        targetPath: '$(System.DefaultWorkingDirectory)/manifests'
    - task: KubernetesManifest@00
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'aws-kubernetes-cluster-service-connection' # nombre de la conexión de servicio de Kubernetes
        namespace: 'default' # espacio de nombres de Kubernetes donde se desplegarán los manifiestos
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml' # ruta a los manifiestos de Kubernetes descargados
        containers: wwun/currency-exchange-devops:$(tag) # nombre del contenedor y la etiqueta que se utilizarán en el despliegue